### ISSUE TITLE
concurrently requires Quotes around the Commands on Windows

### ISSUE THREAD

**Issue by frastlin** [perminder-klair/feathersjs-react-js#3]
With concurrently installed type:
npm run start-dev
and you get a whole lot of errors, mostly that nod, src, wb... are not commands. What is going on is that concurrently needs double quotes and not single quotes. It should look like:
    "start-dev": "concurrently \"node src/\" \"nwb serve-react-app app/index.js\"",

**Comment by perminder-klair** [comment]
@frastlin thanks I see with Mac OS it has no issue, it occurs in Windows. I will do update with this fix.
